name: smallTasksNix
version: 0.1.0.0

# a set of basic libraries used by most apps
dependencies:
  - base >= 4.7 && < 5
  - rio
  - typed-process

library:
  source-dirs: src

executables:
  smallTasksNix:
    main: Main.hs
    source-dirs: bin
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smallTasksNix

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - smallTasksNix

default-extensions:
  - InstanceSigs
  - ImportQualifiedPost
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
